- obs space:
    name: aircraft
    obsdatain:
      obsfile: InDBDir/aircraft_obs_2018041500.h5
      max frame size: 40000
    obsdataout:
      obsfile: OutDBDir/obsPrefix_AppType_aircraft.h5
      max frame size: 40000
    simulated variables: [air_temperature, eastward_wind, northward_wind, specific_humidity]
  obs operator:
    name: VertInterp
  obs error:
    covariance model: diagonal
  obs filters:
  - filter: PreQC
    maxvalue: 3
  get values:
    interpolation type: ObsInterpolationType
